# Generated by Django 2.2 on 2020-02-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artykul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=1024)),
                ('opis', models.TextField()),
                ('file', models.FileField(upload_to='documents/')),
                ('data_publikacji', models.DateTimeField()),
            ],
        ),
    ]
