# Generated by Django 2.2 on 2020-02-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artykul', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artykul',
            old_name='data_publikacji',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='artykul',
            old_name='opis',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='artykul',
            old_name='file',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='artykul',
            old_name='tytul',
            new_name='Title',
        ),
    ]
